### ISSUE TITLE
Deprecation of package - or revamp?

### ISSUE THREAD

**Issue by aleksanderbl29** [56north/geoDK#4]
Hi @mikkelkrogsholm 

I'm interested in creating a package with geographical Danish data and can see that your package already offers this. However, there have been no changes to the package in the last several years. 

I really like the package name as it perfectly describes what the package provides :). And as far as I know there is usage of this package out there. That's the main reason I'm reaching out.

### This leads me to ask:
- Can we consider the package deprecated?
- If not:
  - Is there a possibility that I can contribute to updating the package to get it up to speed?
  - I would also be willing to take over the development from here.

If I'm overstepping here, then please let me know :-)
Looking forward to hear your thoughts on this!

**Comment by aleksanderbl29** [comment]
Closing this issue.

Based the activitiy stats I see on your profile, I have decided to name my package `{geodk}`. Please do let me know if you have intentions of publishing this package to CRAN so we don't conflict each other :) - You can also throw me an email if we should resolve this in private.

Thanks!

**Comment by mikkelkrogsholm** [comment]
Go ahead 😊

søn. 24. nov. 2024 13.09 skrev Aleksander Bang-Larsen <
***@***.***>:
